module.exports = [
  {
    firstName: 'Платов',
    lastName: 'Алексей',
    telephone: '88005555535',
    gitHub: 'https://github.com/JerseyPl',
    email: 'student@student.ru',
  },
  {
    firstName: 'Чепурнов',
    lastName: 'Григорий',
    telephone: '88995555535',
    gitHub: 'https://github.com/Ybizza504',
    email: 'student1@student.ru',
  },
  {
    firstName: 'Илюшин',
    lastName: 'Владислав',
    telephone: '88995555544',
    gitHub: 'https://github.com/ivo7643',
    email: 'student2@student.ru',
  },
  {
    firstName: 'Жовна',
    lastName: 'Максим',
    telephone: '88995575544',
    gitHub: 'https://github.com/maks-zizu',
    email: 'student3@student.ru',
  },
  {
    firstName: 'Евстигнеев',
    lastName: 'Алексей',
    telephone: '88998575544',
    gitHub: 'https://github.com/aversez',
    email: 'student4@student.ru',
  },
  {
    firstName: 'Шнайдер',
    lastName: 'Алина',
    telephone: '88998585544',
    gitHub: 'https://github.com/Alina-Shnaider',
    email: 'student5@student.ru',
  },
  {
    firstName: 'Объедков',
    lastName: 'Андрей',
    telephone: '88998595544',
    gitHub: 'https://github.com/slime793',
    email: 'student33@student.ru',
  },
  {
    firstName: 'Бабушкин',
    lastName: 'Антон',
    telephone: '88998695544',
    gitHub: 'https://github.com/Antonnoid',
    email: 'student333@student.ru',
  },
  {
    firstName: 'Клепинин',
    lastName: 'Валерий',
    telephone: '88999695544',
    gitHub: 'https://github.com/Valery-Klepinin',
    email: 'student3333@student.ru',
  },
  {
    firstName: 'Набиев',
    lastName: 'Микаил',
    telephone: '88999696544',
    gitHub: 'https://github.com/meechisdeadd',
    email: 'student33333@student.ru',
  },
  {
    firstName: 'Фараджов',
    lastName: 'Эльчин',
    telephone: '88999696744',
    gitHub: 'https://github.com/50chin',
    email: 'studen2222t@student.ru',
  },

];
